### ISSUE TITLE
preview is wrong, see images

### ISSUE THREAD

**Issue by abenz1267** [smjonas/live-command.nvim#13]
Hi,

first of all: this is a nice plugin! So... issue:

![Screenshot_20221006_163728](https://user-images.githubusercontent.com/7055955/194342004-5bc12d96-d20a-44c5-a014-6a724a18f5b6.png)

![Screenshot_20221006_163747](https://user-images.githubusercontent.com/7055955/194342105-cad2a483-84ef-409c-8df7-83af2ca2b9c5.png)

As you can see the preview does not match the result.

Using current neovim stable.

Regards

**Comment by smjonas** [comment]
Hey, thanks for reporting. Is this `vim-surround` or `nvim-surround`? I will look into it.

**Comment by abenz1267** [comment]
There's also a preview problem with

```
Test
Bla
Test
Bla
Test
Bla
```

if i do `:G/Test/d`.

![Screenshot_20221006_164515](https://user-images.githubusercontent.com/7055955/194344122-ea844e97-50a7-4815-9e1b-ad42db265f80.png)

The last "Test" is just gone while the others are red

**Comment by smjonas** [comment]
Both of these now look as expected to me:
![image](https://user-images.githubusercontent.com/40792180/194369338-a58603d9-1373-45ca-9cd1-639ac031d678.png)
---
![image](https://user-images.githubusercontent.com/40792180/194369431-45618336-3301-4253-9863-02b6f762e018.png)
