### ISSUE TITLE
issues appending to the end `A` with windwp/nvim-autopairs

### ISSUE THREAD

**Issue by sibouras** [smjonas/live-command.nvim#16]
with Norm

https://user-images.githubusercontent.com/64098483/194438561-bbcb43c0-f0e3-475f-ac38-690ac3c98b16.mp4

with G

https://user-images.githubusercontent.com/64098483/194438991-c1f96015-6147-44e0-a8b4-a5eea6bfab67.mp4

**Comment by smjonas** [comment]
For now, you can use this workaround:
```lua
require("nvim-autopairs").setup {
  break_undo = false,
}
```

**Comment by sibouras** [comment]
works great thanks :)

**Comment by smjonas** [comment]
Fixed by https://github.com/neovim/neovim/pull/24289
