### ISSUE TITLE
Nitpick, unimportant, no one cares problem in combination with numb 

### ISSUE THREAD

**Issue by premell** [smjonas/live-command.nvim#25]
I encountered a small issue when using Reg in combination with  [numb](https://github.com/nacro90/numb.nvim). When i try to write 5Reg q it jumps to the fifth row and executes the query there. There is probably nothing to be done about this but id thought i should let you know anyway, feel free to close this

[Screencast from 2023-02-26 17-12-48.webm](https://user-images.githubusercontent.com/65544203/221422352-d47a8074-a239-4914-a6e0-b538bb445fa5.webm)

**Comment by smjonas** [comment]
You can fix this by changing your `numb.nvim` config (see their readme):
```lua
require("numb").setup {
  number_only = true,
}
```
