### ISSUE TITLE
Deleting text leads to strange results

### ISSUE THREAD

**Issue by Mateiadrielrafael** [smjonas/live-command.nvim#27]
For example, I selected two lines and typed `:Norm de`, and then deleted the previous two characters. This made it so another word got deleted on each line. I then pressed `<Esc>` to cancel, which didn't revert one of the deletions.

**Comment by smjonas** [comment]
Thanks for reporting, could you provide some more detailed reproduction steps, e.g. what exactly did you type? I am not sure what you meant with " and then deleted the previous two characters. " (do you mean `de` in the command line?)

**Comment by Mateiadrielrafael** [comment]
yep! I'll record a gif when I'm back at my computer

**Comment by Mateiadrielrafael** [comment]
Hi, I had forgotten about this, but here's a gif:
![image](https://user-images.githubusercontent.com/39400800/227663441-172e3b67-0a60-47dd-905c-1615feeba3be.png)

**Comment by Mateiadrielrafael** [comment]
Wait, does github automstically convert GIFs to pngs or something? I could have sworn that looked fine when I sent it...

**Comment by smjonas** [comment]
> Wait, does github automstically convert GIFs to pngs or something? I could have sworn that looked fine when I sent it...

GitHub definitely used to support GIFs, I think it's still the case. Could you let me know what happened after you typed the command shown in the screenshot?

**Comment by Mateiadrielrafael** [comment]
@smjonas Closing because I cannot reproduce this anymore
