### ISSUE TITLE
Broken when used with cmdheight=0

### ISSUE THREAD

**Issue by Mateiadrielrafael** [smjonas/live-command.nvim#28]
If cmdheight is set to 0, the lualine status bar gets drawn over/behind my cmdline (can't really tell) on each key pressed.

**Comment by Mateiadrielrafael** [comment]
That first description might be a little confusing, so here's a GIF demonstrating the issue: 
![image](https://user-images.githubusercontent.com/39400800/227663751-73094c39-87a6-48a3-97a5-c7eb43468abd.png)

After I type the first `d`, my bar gets displayed behind my cmdline. I'm not sure what causes this, but I assume it's something to do with redraws. I can't find a way to replicate this with the built in `%s//` live preview.

**Comment by smjonas** [comment]
This seems to be no longer an issue on the latest Neovim nightly version.
