### ISSUE TITLE
Question/Brainstorming: Recommendation for managing macros

### ISSUE THREAD

**Issue by matu3ba** [smjonas/live-command.nvim#3]
Do you have a recommendation for storing and loading macros with lua?

1. If I store them inside the lua file, stylua gets invalid UTF8 errors.
2. Macros tend to be tailored to a language or project, so storing them in another repo (not with the dotfiles) sounds like a good idea.
3. I did not find anything in lua yet.
4. Macro debugging is horribly hard. They fail silently and may fail with or without any action. Any kind of visually highlighting that "something was changed" and "it failed" would be helpful.
5. It would be extremely helpful, if there could be a highlighting of lines, which a macro can be applied to. Think of single and multiline code inside switches,if-else prongs, where one wants to know that each switch case/if-else works before trying.
6. Checking for "marker symbols inside the line/section" before applying the macro and saving this info alongside the macro would be awesome. This would allow fast inspection, if the macro "would do something". Logic could be applied on top of that.

Please let me know, what you think of those ideas and how to structure them into actionable items (for investigation).

**Comment by smjonas** [comment]
Hey, thanks for checking out my plugin! Regarding your questions:
> 1. If I store them inside the lua file, stylua gets invalid UTF8 errors.

Could you give an example for that? For me, it works to surround the macro in `[[ ]]` brackets as a string and store it as a local variable. This way, you can also store special characters such as `<Esc>` entered by typing `<C-v><Esc>`. Though, there are probably some edge cases. However, I am currently not aware of any plugin that generates macros from these strings.

> 3. I did not find anything in lua yet.

Even though, it's not in Lua, did you check out https://github.com/svermeulen/vim-macrobatics? This plugin seems to contain many features regarding managing of macros.

> 4. Macro debugging is horribly hard. They fail silently and may fail with or without any action. Any kind of visually highlighting that "something was changed" and "it failed" would be helpful.

That is actually a usecase of this plugin and one reason why I started creating it. Essentially, you would use the `:Norm` command to test out the series of commands you want to apply. While typing, you get visual feedback and modify the arguments until it does what you want. You will be able to see deletions, replacements and insertions separately, by default highlighted in different colors.

After you ran the command, you can then store the command as a macro. (Did you know about `<C-f>` in commandline mode?)

> 5. It would be extremely helpful, if there could be a highlighting of lines, which a macro can be applied to. Think of single and multiline code inside switches,if-else prongs, where one wants to know that each switch case/if-else works before trying.

Not sure I understood you correctly here: could you clarify when a macro *can* and *cannot* be applied to some lines of code? 

> 6. Checking for "marker symbols inside the line/section" before applying the macro and saving this info alongside the macro would be awesome. This would allow fast inspection, if the macro "would do something". Logic could be applied on top of that.

That definitely seems useful, but seems a bit out of scope for this plugin. Maybe there is already a plugin for this though? If not that sounds like a great idea! :)

**Comment by smjonas** [comment]
> This will work on case 1, but not on case 2, because there is no ".

Ah got you. Unfortunately, I am fairly certain that there is currently no way in Vim / Nvim to check whether any default motion such as `f` "worked" or not. That could certainly be changed by a plugin which could set `vim.v.errmsg` on failure for example. But until such a feature is available, there is sadly nothing that can be done by my plugin here, sorry.

> But what about doing vice versa?

Sorry, not sure I can follow here. Do you mean that you want to create a command from an existing mapping?

**Comment by matu3ba** [comment]
> Do you mean that you want to create a command from an existing mapping?

Assuming the first problem has been solved, one could translate the functionality to lua (including an error message) "for debugging". This sounds less error-prone to me and one could use the debug infrastructure for neovim + lua then.

**Comment by smjonas** [comment]
Closing since there is nothing actionable by my plugin currently :) Feel free to reopen if you think there are concrete things that can be improved.
