### ISSUE TITLE
Heads up, your video demos don't load properly on Safari

### ISSUE THREAD

**Issue by unphased** [smjonas/live-command.nvim#30]
I tried debugging it with safari devtools but couldn't really find anything conclusive. the video file (e.g. https://user-images.githubusercontent.com/40792180/194180320-691efe71-0743-40e5-b0d7-454f142a9235.mp4) just refuses to load and it seems security related.

**Comment by smjonas** [comment]
Thanks for letting me know, I wasn't aware of that!
