### ISSUE TITLE
Installation with Plug ?

### ISSUE THREAD

**Issue by edi9999** [smjonas/live-command.nvim#33]
I'm still using https://github.com/junegunn/vim-plug/.

Do you know how to install live-command.nvim with that ?

It would be great having this info in the README. I think it is using packer.nvim in your installation instructions but I'm not sure about that.

**Comment by smjonas** [comment]
You should be able to install it as follows from your `init.vim`:
```vim
Plug 'smjonas/live-command.nvim'
lua << EOF
require("live-command").setup {
  -- ... put your commands here (see readme)
}
EOF
```
Notice that I called the `setup` function directly from Vimscript. Alternatively, you can also call it from a separate Lua file (e.g. with a `init.lua`).

**Comment by edi9999** [comment]
Can you add this exact command to your readme for other users ?

I really like this plugin !

**Comment by smjonas** [comment]
Yes I could do that :) Glad you like the plugin!
