### ISSUE TITLE
The defaults highlight config does not seem to work

### ISSUE THREAD

**Issue by jdhao** [smjonas/live-command.nvim#39]
The settings for the highlight in the default does not seem to work. I am using the following config:

```
require("live-command").setup {
  defaults = {
    enable_highlighting = false,
    inline_highlighting = false,
  },
}
```

Whether i set up `enable_highlighting` to true or false, I can still see the highlight for the changed text. The `inline_highlighting` option also does not seem to make any effect whether it is true or false.

**Comment by smjonas** [comment]
Oops, another case of me forgetting to update the documentation... that's what happens when you keep a PR open for so long :sweat_smile:. Anyway, I will adjust the docs and migration guide.

For now, you can just use
```lua
require("live-command").setup {
  enable_highlighting = false,
  inline_highlighting = false,
}
```

**Comment by smjonas** [comment]
I updated the docs, migration guide and improved the detection of using unsupported features (either when the `defaults` table is used or when commands are customized individually).

**Comment by jdhao** [comment]
Thanks, I will update later
