### ISSUE TITLE
How to preview :g commands

### ISSUE THREAD

**Issue by AckslD** [smjonas/live-command.nvim#7]
Can this plugin be used to preview `:g`? For example lets say I have the buffer:
```
foo
bar
barx
foo
xbar
```
and I want to delete any line containing `bar` which could be done with `:g/bar/d<CR>`. However if I add the entry `G = { cmd = 'g' }` to the config of this plugin. It only previews the command on the current line when I type `:G/bar/d`, even though `:g` acts on all lines.

**Comment by smjonas** [comment]
That's a nice usecase! I have now fixed a few bugs on the main branch (note that visualizing deletions won't work on main now, I'll get to that once I have finished work on the `hl_improvements` branch :D). Please try changing your command to `G = { cmd = 'g' , range = { 1, -1, kind = "absolute" } }`.

**Comment by AckslD** [comment]
Thanks for a quick reply! I tried your suggestion but now I don't get any preview, but maybe that's related to deletions not working as you mentioned since `:g/bar/d` will only delete?

**Comment by smjonas** [comment]
Sorry, my earlier fix was a bit too rushed :smile: I have now fixed several bugs related to the handling of ranges, could you try again with the latest commit? Highlights should now also work again.

**Comment by AckslD** [comment]
Seems to not have done it unfortunately, I'm getting the original behaviour for both this and #6 now.

**Comment by smjonas** [comment]
Ok, for this issue, please change `range` to `hl_range`, that was a typo in my earlier comment. I reopened your other issue :)

**Comment by AckslD** [comment]
Ah! Yes this works, thanks :heart: :rocket:

**Comment by smjonas** [comment]
I noticed there was pretty bad performance when using your `G` command in large files. I have now added `hl_range = { kind = "visible" }` to only preview lines in the current buffer which speeds up things dramatically!

**Comment by AckslD** [comment]
Ah that's awesome!

**Comment by uloco** [comment]
This is really nice. Is there a way to also highlight the found patterns like :g does at first, before applying the command? @AckslD @smjonas
